program: train_sweep.py
method: grid
name: sweep
metric:
  goal: minimize
  name: test/loss_kl
parameters:
  batch_size:
    value: 32
  num_workers:
    value: 2
  num_epochs:
    value: 200
  lr:
    values: [0.01, 0.005, 0.001, 0.0005, 0.0001]
  wd:
    value: 0.001
  step_size:
    value: 10
  gamma:
    value: 0.7
