program: train_sweep.py
method: grid
name: sweep
metric:
  goal: minimize
  name: test/loss_kl
parameters:
  batch_size:
    value: 32
  num_workers:
    value: 2
  num_epochs:
    value: 200
  lr:
    values: [0.1, 0.01]
  wd:
    values: [0.001, 0.002, 0.003]
  step_size:
    values: [10, 20, 40]
  gamma:
    values: [0.6, 0.7, 0.8]
